language: node_js
node_js:
- '8'
branches:
  only:
  - master
  # npm version tags
  - /^v\d+\.\d+\.\d+$/
cache:
  directories:
  - "$HOME/.npm"
jobs:
  include:
  - name: test
    before_script:
    - npm run lint
  - if: branch = master AND type = pull_request
    name: ember-cli-update
    script:
    - git checkout $TRAVIS_PULL_REQUEST_SHA
    - git checkout -B $TRAVIS_PULL_REQUEST_BRANCH
    - git remote set-url origin https://$GITHUB_TOKEN@github.com/$TRAVIS_PULL_REQUEST_SLUG.git
    - npx https://github.com/kellyselden/ember-cli-update-action.git#semver:^1.3.11 --pull-request-url https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST --autofix-command "npm run lint -- --fix"
  - deploy:
    provider: npm
    email: kellyselden@gmail.com
    api_key:
      secure: F3t+l6SqF2oo8viqCIhZ2KHU6ojAJDOeA48y3RGojXBJC4tae9r5Pxtu//m7Izkz61WZ4Y9rYvmmO6eDqpk8b1EUouBasjg8gTa26H8GO0IvlCdDvTpzCa+ETwEO6GZRCzsL2xg8MHHMTUtd94a0Xrl4wtvrdhUaJzoAAVJHJBuPPsflr7jQWPFeteONtUw57iJv5d947RzJz4lbxmhOx6gXjuWdh3t260EdiJm58K5KKGbc0I4JsfI1eNxChnZeTYezZmpzgLOU6VEkw5aqv+UOM1Em5QGh5EdJy9K1eU0hpzvUPRcfZ858Crfbfgqg/pXZGMmPxD7nZgp05s2FOqly0hrK+pUNRxmKYliCj4wEDbbZm9K5ubMAgMSUO8RVAOekRoTzzbZWPsPpwolTfi2nO9BC1OgKR94CVirltVIDL66ffUEw704p73aju6KqhXtvEgm5l5fkbMhoxnx7qRio/dFsCiLRZMuJpPzrphISFzSnjPMd+CUxXNdv5su5nw/8jhBT32DJhrD6oWWMo/iIYUHCMp+DsietT2WXEApyl7PEGa/BTt+CI+3q3QrME1vQxVLfrsbK+jKYXQry3m2XZFJeNy97Ar9Hm8/4whS4p5izUWfPX2Jm/6fLDOTeYVKacXQBjYaihw8z1hbXzSjsZcI9yhZ4vRHtzadST+E=
    on:
      tags: true
      repo: kellyselden/merge-package.json
